[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd RaadArenda && pnpm install"]

[phases.build]
cmds = ["cd RaadArenda && pnpm run build"]

[start]
cmd = "cd RaadArenda && pnpm run start"
